import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";

import {
  type ResolverResult,
  type ResolverSourceDefinition,
  compositeKey,
  createResolverDiagnostics,
  firstPresent,
  loadResolverSources,
  mergeResolvedRecord,
  normalizedText,
  numberValue,
  recordDedupe,
  sortByRecent,
  textValue,
  toResolverResult,
} from "@/lib/resolvers/_shared";

const MESSAGE_SOURCES: ResolverSourceDefinition[] = [
  {
    table: "chichi_messages",
    classification: "parallel_live_source",
    evidence: "code",
    description: "Private or internal ChiChi assistant messages.",
    limit: 10000,
  },
  {
    table: "chichi_public_messages",
    classification: "parallel_live_source",
    evidence: "code",
    description: "Public/site ChiChi assistant messages.",
    limit: 10000,
  },
];

const THREAD_SOURCES: ResolverSourceDefinition[] = [
  {
    table: "chichi_threads",
    classification: "parallel_live_source",
    evidence: "code",
    description: "Private/internal ChiChi threads.",
    limit: 5000,
  },
  {
    table: "chichi_public_threads",
    classification: "parallel_live_source",
    evidence: "code",
    description: "Public/site ChiChi threads.",
    limit: 5000,
  },
  {
    table: "chichi_public_daily_summary",
    classification: "derived_support_view",
    evidence: "runtime_candidate",
    description: "Derived public ChiChi summary view.",
    limit: 5000,
  },
];

const ALERT_SOURCES: ResolverSourceDefinition[] = [
  {
    table: "chichi_admin_alerts",
    classification: "parallel_live_source",
    evidence: "migration",
    description: "Admin intelligence alerts generated by ChiChi.",
    limit: 5000,
  },
  {
    table: "chichi_admin_digests",
    classification: "parallel_live_source",
    evidence: "migration",
    description: "Admin digest summaries generated by ChiChi.",
    limit: 365,
  },
  {
    table: "chichi_admin_digest",
    classification: "parallel_live_source",
    evidence: "runtime_candidate",
    description: "Legacy or alternate ChiChi admin digest table name.",
    limit: 365,
  },
];

const MEMORY_SOURCES: ResolverSourceDefinition[] = [
  {
    table: "chichi_memory_records",
    classification: "parallel_live_source",
    evidence: "migration",
    description: "Current ChiChi memory store.",
    limit: 5000,
  },
  {
    table: "chichi_memory",
    classification: "parallel_live_source",
    evidence: "runtime_candidate",
    description: "Legacy ChiChi memory store.",
    limit: 5000,
  },
];

export type ResolvedChiChiMessage = {
  id: string;
  threadId: string | null;
  sourceTable: string;
  channelType: "admin" | "public";
  senderRole: string | null;
  buyerId: number | null;
  puppyId: number | null;
  body: string | null;
  createdAt: string | null;
};

export type ResolvedChiChiThread = {
  id: string;
  sourceTable: string;
  channelType: "admin" | "public";
  buyerId: number | null;
  puppyId: number | null;
  title: string | null;
  summary: string | null;
  leadStatus: string | null;
  followUpNeeded: boolean | null;
  tags: string[];
  updatedAt: string | null;
  messages: ResolvedChiChiMessage[];
};

export type ResolvedChiChiAlert = {
  id: string;
  sourceTable: string;
  severity: string | null;
  title: string | null;
  message: string | null;
  buyerId: number | null;
  puppyId: number | null;
  createdAt: string | null;
  resolved: boolean;
};

export type ResolvedChiChiDigest = {
  id: string;
  sourceTable: string;
  digestDate: string | null;
  summary: string | null;
  priorities: string[];
  createdAt: string | null;
};

export type ResolvedChiChiMemory = {
  id: string;
  sourceTable: string;
  buyerId: number | null;
  puppyId: number | null;
  scope: string | null;
  memoryKey: string | null;
  summary: string | null;
  updatedAt: string | null;
};

export type ResolvedChiChiWorkspace = {
  resolvedChiChiMessages: ResolvedChiChiMessage[];
  resolvedChiChiThreads: ResolvedChiChiThread[];
  resolvedChiChiAlerts: ResolvedChiChiAlert[];
  resolvedChiChiDigests: ResolvedChiChiDigest[];
  resolvedChiChiMemory: ResolvedChiChiMemory[];
};

function channelTypeForTable(table: string) {
  return table.includes("public") ? "public" : "admin";
}

function normalizeMessage(
  sourceTable: string,
  row: Record<string, unknown>
): ResolvedChiChiMessage {
  const id =
    textValue(row, "id") ||
    compositeKey(sourceTable, textValue(row, "thread_id"), textValue(row, "created_at"), textValue(row, "message")) ||
    sourceTable;
  return {
    id: `${sourceTable}:${id}`,
    threadId: firstPresent(textValue(row, "thread_id"), textValue(row, "conversation_id")) ?? null,
    sourceTable,
    channelType: channelTypeForTable(sourceTable),
    senderRole:
      firstPresent(textValue(row, "sender_role"), textValue(row, "role"), textValue(row, "sender")) ??
      null,
    buyerId: numberValue(row, "buyer_id"),
    puppyId: numberValue(row, "puppy_id"),
    body:
      firstPresent(textValue(row, "body"), textValue(row, "message"), textValue(row, "content")) ??
      null,
    createdAt: firstPresent(textValue(row, "created_at"), textValue(row, "updated_at")) ?? null,
  };
}

function normalizeThread(
  sourceTable: string,
  row: Record<string, unknown>
): ResolvedChiChiThread {
  const id =
    textValue(row, "id") ||
    compositeKey(sourceTable, textValue(row, "created_at"), textValue(row, "visitor_id")) ||
    sourceTable;
  return {
    id: String(id),
    sourceTable,
    channelType: channelTypeForTable(sourceTable),
    buyerId: numberValue(row, "buyer_id"),
    puppyId: numberValue(row, "puppy_id"),
    title: firstPresent(textValue(row, "title"), textValue(row, "subject")) ?? null,
    summary: firstPresent(textValue(row, "summary"), textValue(row, "intent_summary")) ?? null,
    leadStatus: firstPresent(textValue(row, "lead_status"), textValue(row, "status")) ?? null,
    followUpNeeded: row.follow_up_needed === undefined ? null : Boolean(row.follow_up_needed),
    tags: Array.isArray(row.tags)
      ? row.tags.map((value) => String(value || "").trim()).filter(Boolean)
      : [],
    updatedAt: firstPresent(textValue(row, "updated_at"), textValue(row, "created_at")) ?? null,
    messages: [],
  };
}

function normalizeAlert(
  sourceTable: string,
  row: Record<string, unknown>
): ResolvedChiChiAlert | null {
  if (!sourceTable.includes("alerts")) return null;
  const id =
    textValue(row, "id") ||
    compositeKey(sourceTable, textValue(row, "created_at"), textValue(row, "title")) ||
    sourceTable;
  return {
    id: `${sourceTable}:${id}`,
    sourceTable,
    severity: firstPresent(textValue(row, "tone"), textValue(row, "severity")) ?? null,
    title: textValue(row, "title"),
    message: textValue(row, "message"),
    buyerId: numberValue(row, "buyer_id"),
    puppyId: numberValue(row, "puppy_id"),
    createdAt: firstPresent(textValue(row, "created_at"), textValue(row, "updated_at")) ?? null,
    resolved: ["resolved", "closed", "complete"].includes(normalizedText(textValue(row, "status"))),
  };
}

function normalizeDigest(
  sourceTable: string,
  row: Record<string, unknown>
): ResolvedChiChiDigest | null {
  if (!sourceTable.includes("digest")) return null;
  const id =
    textValue(row, "id") ||
    compositeKey(sourceTable, textValue(row, "digest_date"), textValue(row, "created_at")) ||
    sourceTable;
  return {
    id: `${sourceTable}:${id}`,
    sourceTable,
    digestDate: firstPresent(textValue(row, "digest_date"), textValue(row, "created_at")) ?? null,
    summary: textValue(row, "summary"),
    priorities: Array.isArray(row.priorities)
      ? row.priorities.map((value) => String(value || "").trim()).filter(Boolean)
      : [],
    createdAt: firstPresent(textValue(row, "created_at"), textValue(row, "updated_at")) ?? null,
  };
}

function normalizeMemory(
  sourceTable: string,
  row: Record<string, unknown>
): ResolvedChiChiMemory {
  const id =
    textValue(row, "id") ||
    compositeKey(sourceTable, textValue(row, "memory_key"), textValue(row, "updated_at")) ||
    sourceTable;
  return {
    id: `${sourceTable}:${id}`,
    sourceTable,
    buyerId: numberValue(row, "buyer_id"),
    puppyId: numberValue(row, "puppy_id"),
    scope: textValue(row, "scope"),
    memoryKey: textValue(row, "memory_key"),
    summary:
      firstPresent(textValue(row, "summary"), textValue(row, "memory_text"), textValue(row, "content")) ??
      null,
    updatedAt: firstPresent(textValue(row, "updated_at"), textValue(row, "created_at")) ?? null,
  };
}

async function resolveChiChiState(service: SupabaseClient) {
  const [messageSources, threadSources, alertSources, memorySources] = await Promise.all([
    loadResolverSources(service, MESSAGE_SOURCES),
    loadResolverSources(service, THREAD_SOURCES),
    loadResolverSources(service, ALERT_SOURCES),
    loadResolverSources(service, MEMORY_SOURCES),
  ]);

  const diagnostics = createResolverDiagnostics("chichi", [
    ...messageSources,
    ...threadSources,
    ...alertSources,
    ...memorySources,
  ]);

  const resolvedChiChiMessages = sortByRecent(
    messageSources.flatMap((source) => source.rows.map((row) => normalizeMessage(source.table, row))),
    "createdAt"
  );

  const threadMap = new Map<string, ResolvedChiChiThread>();
  threadSources
    .filter((source) => !source.table.includes("daily_summary"))
    .forEach((source) => {
      source.rows.forEach((row) => {
        const normalized = normalizeThread(source.table, row);
        const key = `${normalized.channelType}:${normalized.id}`;
        const existing = threadMap.get(key);
        if (!existing) {
          threadMap.set(key, normalized);
          return;
        }
        threadMap.set(
          key,
          mergeResolvedRecord(
            existing,
            normalized,
            diagnostics,
            `ChiChi thread ${normalized.id}`,
            ["summary", "leadStatus", "updatedAt", "buyerId", "puppyId", "followUpNeeded"]
          )
        );
        recordDedupe(diagnostics);
      });
    });

  resolvedChiChiMessages.forEach((message) => {
    if (!message.threadId) return;
    const key = `${message.channelType}:${message.threadId}`;
    const thread = threadMap.get(key);
    if (!thread) return;
    thread.messages.push(message);
    if (thread.buyerId === null && message.buyerId !== null) thread.buyerId = message.buyerId;
    if (thread.puppyId === null && message.puppyId !== null) thread.puppyId = message.puppyId;
  });

  const resolvedChiChiThreads = sortByRecent(
    Array.from(threadMap.values()).map((thread) => ({
      ...thread,
      messages: sortByRecent(thread.messages, "createdAt"),
    })),
    "updatedAt"
  );

  const resolvedChiChiAlerts = sortByRecent(
    alertSources
      .flatMap((source) => source.rows.map((row) => normalizeAlert(source.table, row)).filter(Boolean)) as ResolvedChiChiAlert[],
    "createdAt"
  );

  const resolvedChiChiDigests = sortByRecent(
    alertSources
      .flatMap((source) => source.rows.map((row) => normalizeDigest(source.table, row)).filter(Boolean)) as ResolvedChiChiDigest[],
    "digestDate",
    "createdAt"
  );

  const resolvedChiChiMemory = sortByRecent(
    memorySources.flatMap((source) => source.rows.map((row) => normalizeMemory(source.table, row))),
    "updatedAt"
  );

  return toResolverResult<ResolvedChiChiWorkspace>(
    {
      resolvedChiChiMessages,
      resolvedChiChiThreads,
      resolvedChiChiAlerts,
      resolvedChiChiDigests,
      resolvedChiChiMemory,
    },
    diagnostics
  );
}

export async function resolveChiChiMessages(
  service: SupabaseClient
): Promise<ResolverResult<ResolvedChiChiMessage[]>> {
  const resolved = await resolveChiChiState(service);
  return {
    data: resolved.data.resolvedChiChiMessages,
    diagnostics: resolved.diagnostics,
  };
}

export async function resolveChiChiThreads(
  service: SupabaseClient
): Promise<ResolverResult<ResolvedChiChiThread[]>> {
  const resolved = await resolveChiChiState(service);
  return {
    data: resolved.data.resolvedChiChiThreads,
    diagnostics: resolved.diagnostics,
  };
}

export async function resolveChiChiAlerts(
  service: SupabaseClient
): Promise<ResolverResult<ResolvedChiChiAlert[]>> {
  const resolved = await resolveChiChiState(service);
  return {
    data: resolved.data.resolvedChiChiAlerts,
    diagnostics: resolved.diagnostics,
  };
}

export async function resolveChiChiMemory(
  service: SupabaseClient
): Promise<ResolverResult<ResolvedChiChiMemory[]>> {
  const resolved = await resolveChiChiState(service);
  return {
    data: resolved.data.resolvedChiChiMemory,
    diagnostics: resolved.diagnostics,
  };
}

export async function resolveChiChiWorkspace(
  service: SupabaseClient
): Promise<ResolverResult<ResolvedChiChiWorkspace>> {
  return resolveChiChiState(service);
}
