create table if not exists public.chichi_admin_digests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  digest_date date not null unique,
  summary text not null,
  stats jsonb not null default '{}'::jsonb,
  priorities jsonb not null default '[]'::jsonb,
  source text not null default 'daily',
  generated_at timestamptz not null default now()
);

create index if not exists chichi_admin_digests_date_idx
  on public.chichi_admin_digests (digest_date desc);

create or replace function public.set_chichi_admin_digests_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_chichi_admin_digests_updated_at on public.chichi_admin_digests;

create trigger trg_chichi_admin_digests_updated_at
before update on public.chichi_admin_digests
for each row
execute function public.set_chichi_admin_digests_updated_at();
