create table if not exists public.breeding_dogs (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('dam', 'sire')),
  display_name text not null,
  registered_name text,
  call_name text,
  status text not null default 'active',
  date_of_birth date,
  color text,
  coat_type text,
  registration_no text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.litters (
  id bigint generated by default as identity primary key,
  litter_code text not null,
  litter_name text,
  dam_id bigint references public.breeding_dogs(id) on delete restrict,
  sire_id bigint references public.breeding_dogs(id) on delete restrict,
  whelp_date date,
  status text not null default 'planned',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists litters_litter_code_key on public.litters (litter_code);
create index if not exists litters_dam_id_idx on public.litters (dam_id);
create index if not exists litters_sire_id_idx on public.litters (sire_id);

alter table public.puppies
  add column if not exists litter_id bigint,
  add column if not exists litter_name text,
  add column if not exists dam_id bigint,
  add column if not exists sire_id bigint,
  add column if not exists list_price numeric(10,2);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'puppies_litter_id_fkey'
  ) then
    alter table public.puppies
      add constraint puppies_litter_id_fkey
      foreign key (litter_id) references public.litters(id) on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'puppies_dam_id_fkey'
  ) then
    alter table public.puppies
      add constraint puppies_dam_id_fkey
      foreign key (dam_id) references public.breeding_dogs(id) on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'puppies_sire_id_fkey'
  ) then
    alter table public.puppies
      add constraint puppies_sire_id_fkey
      foreign key (sire_id) references public.breeding_dogs(id) on delete set null;
  end if;
end $$;

create index if not exists puppies_litter_id_idx on public.puppies (litter_id);
create index if not exists puppies_dam_id_idx on public.puppies (dam_id);
create index if not exists puppies_sire_id_idx on public.puppies (sire_id);

update public.puppies
set list_price = price
where list_price is null
  and price is not null;

create or replace function public.touch_lineage_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists breeding_dogs_touch_updated_at on public.breeding_dogs;
create trigger breeding_dogs_touch_updated_at
before update on public.breeding_dogs
for each row
execute function public.touch_lineage_updated_at();

drop trigger if exists litters_touch_updated_at on public.litters;
create trigger litters_touch_updated_at
before update on public.litters
for each row
execute function public.touch_lineage_updated_at();

create or replace function public.sync_puppy_lineage_from_litter()
returns trigger
language plpgsql
as $$
declare
  litter_row public.litters%rowtype;
  dam_name text;
  sire_name text;
begin
  if new.litter_id is null then
    return new;
  end if;

  select *
  into litter_row
  from public.litters
  where id = new.litter_id;

  if not found then
    return new;
  end if;

  new.dam_id = litter_row.dam_id;
  new.sire_id = litter_row.sire_id;
  new.litter_name = coalesce(litter_row.litter_name, litter_row.litter_code, new.litter_name);

  if litter_row.dam_id is not null then
    select display_name into dam_name from public.breeding_dogs where id = litter_row.dam_id;
    new.dam = coalesce(dam_name, new.dam);
  end if;

  if litter_row.sire_id is not null then
    select display_name into sire_name from public.breeding_dogs where id = litter_row.sire_id;
    new.sire = coalesce(sire_name, new.sire);
  end if;

  return new;
end;
$$;

drop trigger if exists puppies_sync_lineage_from_litter on public.puppies;
create trigger puppies_sync_lineage_from_litter
before insert or update of litter_id on public.puppies
for each row
execute function public.sync_puppy_lineage_from_litter();

update public.puppies p
set
  dam_id = l.dam_id,
  sire_id = l.sire_id,
  litter_name = coalesce(p.litter_name, l.litter_name, l.litter_code)
from public.litters l
where p.litter_id = l.id
  and (
    p.dam_id is distinct from l.dam_id
    or p.sire_id is distinct from l.sire_id
    or p.litter_name is null
  );

update public.puppies p
set dam = d.display_name
from public.breeding_dogs d
where p.dam_id = d.id
  and p.dam is distinct from d.display_name;

update public.puppies p
set sire = s.display_name
from public.breeding_dogs s
where p.sire_id = s.id
  and p.sire is distinct from s.display_name;

create or replace view public.lineage_litter_stats as
select
  l.id,
  l.litter_code,
  l.litter_name,
  l.dam_id,
  dam.display_name as dam_name,
  l.sire_id,
  sire.display_name as sire_name,
  l.whelp_date,
  l.status,
  count(p.id)::int as total_puppies,
  count(*) filter (where lower(coalesce(p.status, '')) like '%available%' or lower(coalesce(p.status, '')) like '%expect%')::int as available_count,
  count(*) filter (where lower(coalesce(p.status, '')) like '%reserv%')::int as reserved_count,
  count(*) filter (where lower(coalesce(p.status, '')) in ('completed', 'complete') or lower(coalesce(p.status, '')) like '%sold%' or lower(coalesce(p.status, '')) like '%adopt%' or lower(coalesce(p.status, '')) like '%matched%')::int as completed_count,
  coalesce(sum(coalesce(b.deposit_amount, p.deposit, 0)), 0)::numeric(10,2) as total_deposit_amount,
  coalesce(sum(case when lower(coalesce(p.status, '')) like '%reserv%' then coalesce(b.sale_price, p.price, p.list_price, 0) else 0 end), 0)::numeric(10,2) as reserved_revenue,
  coalesce(sum(case when lower(coalesce(p.status, '')) in ('completed', 'complete') or lower(coalesce(p.status, '')) like '%sold%' or lower(coalesce(p.status, '')) like '%adopt%' or lower(coalesce(p.status, '')) like '%matched%' then coalesce(b.sale_price, p.price, p.list_price, 0) else 0 end), 0)::numeric(10,2) as realized_revenue,
  coalesce(sum(case when lower(coalesce(p.status, '')) like '%available%' or lower(coalesce(p.status, '')) like '%expect%' then coalesce(p.list_price, p.price, 0) else 0 end), 0)::numeric(10,2) as projected_revenue,
  coalesce(avg(nullif(coalesce(b.sale_price, p.price, p.list_price, 0), 0)), 0)::numeric(10,2) as average_sale_price
from public.litters l
left join public.breeding_dogs dam on dam.id = l.dam_id
left join public.breeding_dogs sire on sire.id = l.sire_id
left join public.puppies p on p.litter_id = l.id
left join public.buyers b on b.id = p.buyer_id or b.puppy_id = p.id
group by l.id, dam.display_name, sire.display_name;

create or replace view public.lineage_breeding_dog_stats as
with dog_puppies as (
  select
    dog.id as breeding_dog_id,
    dog.role,
    l.id as litter_id,
    p.id as puppy_id,
    lower(coalesce(p.status, '')) as puppy_status,
    coalesce(b.sale_price, p.price, p.list_price, 0) as sale_value,
    coalesce(b.deposit_amount, p.deposit, 0) as deposit_value
  from public.breeding_dogs dog
  left join public.litters l
    on (dog.role = 'dam' and l.dam_id = dog.id)
    or (dog.role = 'sire' and l.sire_id = dog.id)
  left join public.puppies p on p.litter_id = l.id
  left join public.buyers b on b.id = p.buyer_id or b.puppy_id = p.id
)
select
  dog.id,
  dog.role,
  dog.display_name,
  dog.status,
  count(distinct dog_puppies.litter_id)::int as total_litters,
  count(distinct dog_puppies.puppy_id)::int as total_puppies,
  count(distinct dog_puppies.puppy_id) filter (where dog_puppies.puppy_status like '%available%' or dog_puppies.puppy_status like '%expect%')::int as available_count,
  count(distinct dog_puppies.puppy_id) filter (where dog_puppies.puppy_status like '%reserv%')::int as reserved_count,
  count(distinct dog_puppies.puppy_id) filter (where dog_puppies.puppy_status in ('completed', 'complete') or dog_puppies.puppy_status like '%sold%' or dog_puppies.puppy_status like '%adopt%' or dog_puppies.puppy_status like '%matched%')::int as completed_count,
  coalesce(sum(dog_puppies.deposit_value), 0)::numeric(10,2) as total_deposit_amount,
  coalesce(sum(case when dog_puppies.puppy_status like '%reserv%' then dog_puppies.sale_value else 0 end), 0)::numeric(10,2) as reserved_revenue,
  coalesce(sum(case when dog_puppies.puppy_status in ('completed', 'complete') or dog_puppies.puppy_status like '%sold%' or dog_puppies.puppy_status like '%adopt%' or dog_puppies.puppy_status like '%matched%' then dog_puppies.sale_value else 0 end), 0)::numeric(10,2) as realized_revenue,
  coalesce(avg(nullif(dog_puppies.sale_value, 0)), 0)::numeric(10,2) as average_sale_price
from public.breeding_dogs dog
left join dog_puppies on dog_puppies.breeding_dog_id = dog.id
group by dog.id;
