create table if not exists public.chichi_admin_alerts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  external_event_id text not null unique,
  event_type text null,
  alert_scope text not null default 'payment',
  title text not null,
  message text not null,
  tone text not null default 'success' check (tone in ('success', 'warning', 'danger', 'neutral')),
  buyer_id bigint null references public.buyers (id) on delete set null,
  puppy_id bigint null references public.puppies (id) on delete set null,
  user_id uuid null references auth.users (id) on delete set null,
  payment_id text null,
  payment_link_id text null,
  reference_id text null,
  source text not null default 'zoho_payments',
  meta jsonb not null default '{}'::jsonb
);

create index if not exists chichi_admin_alerts_created_at_idx
  on public.chichi_admin_alerts (created_at desc);

create index if not exists chichi_admin_alerts_scope_idx
  on public.chichi_admin_alerts (alert_scope, created_at desc);

create index if not exists chichi_admin_alerts_buyer_idx
  on public.chichi_admin_alerts (buyer_id, created_at desc);

create or replace function public.set_chichi_admin_alerts_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_chichi_admin_alerts_updated_at on public.chichi_admin_alerts;

create trigger trg_chichi_admin_alerts_updated_at
before update on public.chichi_admin_alerts
for each row
execute function public.set_chichi_admin_alerts_updated_at();
